Album.create!(title: "Visceral Skies", album_type: "EP", artist_id: Artist.first.id, release_date: ("2014-7-8"), image_url: "temp")
Album.create!(title: "Wormhole Karma", album_type: "Album", artist_id: Artist.first.id, release_date: ("2016-9-30"), image_url: "temp")
Album.create!(title: "Inferno Room", album_type: "Album", artist_id: Artist.first.id, release_date: ("2018-12-25"), image_url: "temp")
Album.create!(title: "Luna", album_type: "EP", artist_id: Artist.second.id, release_date: ("2014-03-04"), image_url: "temp")
Album.create!(title: "Skylines", album_type: "Album", artist_id: Artist.second.id, release_date: ("2017-01-17"), image_url: "temp")
Album.create!(title: "Paragon", album_type: "EP", artist_id: Artist.second.id, release_date: ("2017-06-16"), image_url: "temp")
Album.create!(title: "Coma Sessions", album_type: "EP", artist_id: Artist.second.id, release_date: ("2016-10-13"), image_url: "temp")
Album.create!(title: "Lost Anyway", album_type: "Album", artist_id: Artist.all[6], release_date: ("2012-12-22"), image_url: "temp")
Album.create!(title: "Portals", album_type: "EP", artist_id: Artist.third, release_date: ("2013-06-30"), image_url: "temp")
Album.create!(title: "Chasing Goats", album_type: "Single", Artist.third, release_date: ("2015-01-20"), image_url: "temp")
Album.create!(title: "Travels", album_type: "Album", artist_id: Artist.all[5], release_date: ("2013-05-17"), image_url: "temp")
Album.create!(title: "Shine You Up", album_type: "EP", artist_id: Artist.fifth, release_date: ("2013-10-01"), image_url: "temp")
Album.create!(title: "Растаял", album_type: "EP", artist_id: Artist.fourth, release_date: ("2014-12-14"), image_url: "temp")
Album.create!(title: "CYBERPUNK", album_type: "Album", artist_id: Artist.all[7], release_date: ("2014-8-20"), image_url: "temp ")


