Album.create(id: 1, title: "Visceral Skies", album_type: "EP", artist_id: 1, release_date: ("2014-7-8"), image_url: "temp")
Album.create(id: 2, title: "Wormhole Karma", album_type: "Album", artist_id: 1, release_date: ("2016-9-30"), image_url: "temp")
Album.create(id: 3, title: "Inferno Room", album_type: "Album", artist_id: 1, release_date: ("2018-12-25"), image_url: "temp")
Album.create(id: 4, title: "Luna", album_type: "EP", artist_id: 2, release_date: ("2014-03-04"), image_url: "temp")
Album.create(id: 5, title: "Skylines", album_type: "Album", artist_id: 2, release_date: ("2017-01-17"), image_url: "temp")
Album.create(id: 6, title: "Paragon", album_type: "EP", artist_id: 2, release_date: ("2017-06-16"), image_url: "temp")
Album.create(id: 7, title: "Coma Sessions", album_type: "EP", artist_id: 2, release_date: ("2016-10-13"), image_url: "temp")
Album.create(id: 8, title: "Lost Anyway", album_type: "Album", artist_id: 7, release_date: ("2012-12-22"), image_url: "temp")
Album.create(id: 9, title: "Portals", album_type: "EP", artist_id: 3, release_date: ("2013-06-30"), image_url: "temp")
Album.create(id: 10, title: "Chasing Goats", album_type: "Single", artist_id: 3, release_date: ("2015-01-20"), image_url: "temp")
Album.create(id: 11, title: "Travels", album_type: "Album", artist_id: 6, release_date: ("2013-05-17"), image_url: "temp")
Album.create(id: 12, title: "Shine You Up", album_type: "EP", artist_id: 5, release_date: ("2013-10-01"), image_url: "temp")
Album.create(id: 13, title: "Растаял", album_type: "EP", artist_id: 4, release_date: ("2014-12-14"), image_url: "temp")
Album.create(id: 14, title: "CYBERPUNK", album_type: "Album", artist_id: 8, release_date: ("2014-8-20"), image_url: "temp ")


